source 'https://github.com/jiaojiaozhe/XAbstractionLibrary-Specs'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!

target 'XAbstractionLibrary-UICommon_Example' do
  pod 'XAbstractionLibrary-UICommon', :path => '../'
  pod 'XXNibBridge'

  target 'XAbstractionLibrary-UICommon_Tests' do
    inherit! :search_paths


  end
end
